# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-24 11:48
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Только на латинице', max_length=255, verbose_name='Название')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание блока')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайтл')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('meta_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='news', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('content', models.TextField(max_length=255, verbose_name='Содержимое')),
                ('sort', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
