# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-24 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_sliderpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_name', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html')),
                ('inner', models.BooleanField(default=False, verbose_name='Внутренняя страница')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='sliders', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
