# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-24 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderpluginmodel',
            name='sub_name',
        ),
    ]
